### ISSUE TITLE
Targetting enemies using ranged button "v" causes crash if there is only one person in sight

### ISSUE THREAD

**Issue by solnyszczko** [amethyst/rustrogueliketutorial#213]
Spawn in game, equip ranged weapon, get to position where only one person is in range, press 'v' twice, crash

**Comment by solnyszczko** [comment]
thread 'main' panicked at 'attempt to subtract with overflow', chapter-75-darkplaza/src/player.rs:104:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by solnyszczko** [comment]
panicked at 'index out of bounds: the len is 1 but the index is 1', /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/slice/mod.rs:2791:10

Stack:

init/imports.wbg.__wbg_new_59cb74e423758ede@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:239:19
console_error_panic_hook::hook::h4ea5740396708e46@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[1262]:0x212ac7
core::ops::function::Fn::call::h6bc7a5f4adf22b4c@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4777]:0x2d7425
std::panicking::rust_panic_with_hook::hd5a9721517b5ba3a@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[2845]:0x2ae775
rust_begin_unwind@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3832]:0x2d033f
core::panicking::panic_fmt::haa65c7c3d08f0deb@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4054]:0x2d3394
core::panicking::panic_bounds_check::h5381761f0b26fc98@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3517]:0x2c978c
chapter_74_darkcity::player::player_input::hc7e1d196c7baa3ff@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[143]:0x598ff
<chapter_74_darkcity::State as bracket_terminal::gamestate::GameState>::tick::h5191bf19febc9d79@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[140]:0x50497
bracket_terminal::hal::wasm::mainloop::tock::h6a2bacdcf5f747a7@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[645]:0x1885e3
<glow::web::RenderLoop as glow::HasRenderLoop>::run::{{closure}}::h1195ce357246454d@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[1551]:0x23ae79
wasm_bindgen::convert::closures::invoke0_mut::hb41e52d670263fe0@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4211]:0x2d4c59
__wbg_adapter_20@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:180:10
real@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:763:24
FrameRequestCallback*init/imports.wbg.__widl_f_request_animation_frame_Window@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:596:39
web_sys::Window::request_animation_frame::h14ee365cc87533ed@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3387]:0x2c5846
<glow::web::RenderLoop as glow::HasRenderLoop>::run::request_animation_frame::h961f7f13680a702f@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3081]:0x2b9994
<glow::web::RenderLoop as glow::HasRenderLoop>::run::{{closure}}::h1195ce357246454d@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[1551]:0x23af13
wasm_bindgen::convert::closures::invoke0_mut::hb41e52d670263fe0@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4211]:0x2d4c59
__wbg_adapter_20@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:180:10
real@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:763:24
FrameRequestCallback*init/imports.wbg.__widl_f_request_animation_frame_Window@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:596:39
web_sys::Window::request_animation_frame::h14ee365cc87533ed@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3387]:0x2c5846
<glow::web::RenderLoop as glow::HasRenderLoop>::run::request_animation_frame::h961f7f13680a702f@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3081]:0x2b9994
<glow::web::RenderLoop as glow::HasRenderLoop>::run::{{closure}}::h1195ce357246454d@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[1551]:0x23af13
wasm_bindgen::convert::closures::invoke0_mut::hb41e52d670263fe0@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4211]:0x2d4c59
__wbg_adapter_20@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:180:10
real@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:763:24
FrameRequestCallback*init/imports.wbg.__widl_f_request_animation_frame_Window@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:596:39
web_sys::Window::request_animation_frame::h14ee365cc87533ed@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3387]:0x2c5846
<glow::web::RenderLoop as glow::HasRenderLoop>::run::request_animation_frame::h961f7f13680a702f@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3081]:0x2b9994
<glow::web::RenderLoop as glow::HasRenderLoop>::run::{{closure}}::h1195ce357246454d@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[1551]:0x23af13
wasm_bindgen::convert::closures::invoke0_mut::hb41e52d670263fe0@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4211]:0x2d4c59
__wbg_adapter_20@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:180:10
real@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:763:24
FrameRequestCallback*init/imports.wbg.__widl_f_request_animation_frame_Window@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:596:39
web_sys::Window::request_animation_frame::h14ee365cc87533ed@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3387]:0x2c5846
<glow::web::RenderLoop as glow::HasRenderLoop>::run::request_animation_frame::h961f7f13680a702f@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3081]:0x2b9994
<glow::web::RenderLoop as glow::HasRenderLoop>::run::{{closure}}::h1195ce357246454d@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[1551]:0x23af13
wasm_bindgen::convert::closures::invoke0_mut::hb41e52d670263fe0@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4211]:0x2d4c59
__wbg_adapter_20@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:180:10
real@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:763:24
FrameRequestCallback*init/imports.wbg.__widl_f_request_animation_frame_Window@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:596:39
web_sys::Window::request_animation_frame::h14ee365cc87533ed@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3387]:0x2c5846
<glow::web::RenderLoop as glow::HasRenderLoop>::run::request_animation_frame::h961f7f13680a702f@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3081]:0x2b9994
<glow::web::RenderLoop as glow::HasRenderLoop>::run::{{closure}}::h1195ce357246454d@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[1551]:0x23af13
wasm_bindgen::convert::closures::invoke0_mut::hb41e52d670263fe0@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4211]:0x2d4c59
__wbg_adapter_20@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:180:10
real@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:763:24
FrameRequestCallback*init/imports.wbg.__widl_f_request_animation_frame_Window@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:596:39
web_sys::Window::request_animation_frame::h14ee365cc87533ed@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3387]:0x2c5846
<glow::web::RenderLoop as glow::HasRenderLoop>::run::request_animation_frame::h961f7f13680a702f@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3081]:0x2b9994
<glow::web::RenderLoop as glow::HasRenderLoop>::run::{{closure}}::h1195ce357246454d@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[1551]:0x23af13
wasm_bindgen::convert::closures::invoke0_mut::hb41e52d670263fe0@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4211]:0x2d4c59
__wbg_adapter_20@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:180:10
real@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:763:24
FrameRequestCallback*init/imports.wbg.__widl_f_request_animation_frame_Window@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:596:39
web_sys::Window::request_animation_frame::h14ee365cc87533ed@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3387]:0x2c5846
<glow::web::RenderLoop as glow::HasRenderLoop>::run::request_animation_frame::h961f7f13680a702f@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3081]:0x2b9994
<glow::web::RenderLoop as glow::HasRenderLoop>::run::{{closure}}::h1195ce357246454d@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[1551]:0x23af13
wasm_bindgen::convert::closures::invoke0_mut::hb41e52d670263fe0@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4211]:0x2d4c59
__wbg_adapter_20@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:180:10
real@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:763:24
FrameRequestCallback*init/imports.wbg.__widl_f_request_animation_frame_Window@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:596:39
web_sys::Window::request_animation_frame::h14ee365cc87533ed@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3387]:0x2c5846
<glow::web::RenderLoop as glow::HasRenderLoop>::run::request_animation_frame::h961f7f13680a702f@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3081]:0x2b9994
<glow::web::RenderLoop as glow::HasRenderLoop>::run::{{closure}}::h1195ce357246454d@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[1551]:0x23af13
wasm_bindgen::convert::closures::invoke0_mut::hb41e52d670263fe0@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4211]:0x2d4c59
__wbg_adapter_20@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:180:10
real@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:763:24
FrameRequestCallback*init/imports.wbg.__widl_f_request_animation_frame_Window@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:596:39
web_sys::Window::request_animation_frame::h14ee365cc87533ed@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3387]:0x2c5846
<glow::web::RenderLoop as glow::HasRenderLoop>::run::request_animation_frame::h961f7f13680a702f@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3081]:0x2b9994
<glow::web::RenderLoop as glow::HasRenderLoop>::run::{{closure}}::h1195ce357246454d@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[1551]:0x23af13
wasm_bindgen::convert::closures::invoke0_mut::hb41e52d670263fe0@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[4211]:0x2d4c59
__wbg_adapter_20@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:180:10
real@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:763:24
FrameRequestCallback*init/imports.wbg.__widl_f_request_animation_frame_Window@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob.js:596:39
web_sys::Window::request_animation_frame::h14ee365cc87533ed@https://bfnightly.bracketproductions.com/rustbook/wasm/chapter-74-darkcity/myblob_bg.wasm:wasm-function[3387]:0x2c5846


myblob.js:251:21
